# fly.toml app configuration file generated for g2historyapi on 2025-05-26T06:24:25Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'g2historyapi'
primary_region = 'cdg'

[build]

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
