name: Sync Matches

on:
  schedule:
    # Cada hora desde las 00:00 hasta las 06:00 UTC
    - cron: '0 0-6 * * *'

    # Cada hora desde las 16:00 hasta las 23:00 UTC
    - cron: '0 16-23 * * *'

  workflow_dispatch:        # Permite lanzarlo manualmente si quieres

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.API_KEY }}
      API_URL: https://g2historyapi.fly.dev/matches/sync
    steps:
      - name: Trigger sync endpoint
        run: |
          curl -X POST "$API_URL" \
            -H "Authorization: Bearer $API_KEY" \
            -H "Content-Type: application/json" \
            -d '{}'
